client_config_backend: settings
client_config:
  client_id: 318841079876-joo33h674cgaubehoer4fbobfsklu0n3.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive.metadata